
name: Deploy Master Branch

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ttl.sh/devopslive-example-${{ github.run_id }}

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build

    permissions:
      deployments: write
      contents: write

    steps:
      - uses: actions/checkout@v3
      - name: Deploy
        uses: WyriHaximus/github-action-helm3@v2
        with:
          exec: |
            helm upgrade --install devopslive-example-${{ github.run_id }} \
              one-image --repo https://helm.sikalabs.io \
              --set image=ttl.sh/devopslive-example-${{ github.run_id }} \
              --set host=devopslive-example-${{ github.run_id }}.k8s.sikademo.com
          kubeconfig: '${{ secrets.KUBECONFIG }}'
      - uses: actions/github-script@v6
        with:
          script: |
            let url = "https://devopslive-example-${{ github.run_id }}.k8s.sikademo.com"
            let deployment = await github.rest.repos.createDeployment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: context.payload.after,
              production_environment: true,
              required_contexts: [],
            })
            github.rest.repos.createDeploymentStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              deployment_id: deployment.data.id,
              state: "success",
              log_url: url,
            })
            github.rest.repos.createCommitComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              commit_sha: context.sha,
              body: "Deployed to "+url,
            });
